### ISSUE TITLE
sass/scss doesn't get compiled to css when building app

### ISSUE THREAD

**Issue by felipefv** [dart-league/ng_bootstrap#122]
I'm having a sass/scss problem on Windows 10, WebStorm 2018.2.5 (Build #WS-182.4892.25, built on October 18, 2018) and Dart 2.0.0.

Those sass/scss files doesn't get compiled to css when building the app. However, when running the app from within Webstorm, they work as expected.

There other issues that are similar to this problem:
- https://github.com/dart-league/ng_bootstrap/issues/48
- https://github.com/dart-league/ng_bootstrap/issues/54
- https://github.com/dart-league/sass_builder/issues/46 (just guessing)

This is my pubspec.yaml:

```
name: angular_test_app
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  angular_forms: any
  ng_bootstrap: any
  http: any

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
```

When building the app for deployment (webdev), the resulting app will specifically miss all.css. Seems like all.scss didn't get compiled for some reason. But why does it happen just when building the app?

P.S. 1: I don't have any file watchers configured on Webstorm. It works "out of the box" (I mean, when I run "index.html").

P.S. 2: pub get --packages-dir breaks webdev building process. It gets stuck at some point.

Thanks in advance.

**Comment by felipefv** [comment]
I've found a solution (or "workaround") for this issue, which I'll describe below.

First I think that it is important to say that I understand that maybe I should've been implementing this solution from the beginning. But, if so, I think that the documentation should mention it.

The solution was mentioned on this issue: https://github.com/dart-league/sass_builder/issues/46 (that I've found later on my research)

1. On dev_dependencies of pubspec.yaml, insert: build_config and sass_builder.
2. Create a build.yaml file on the app's root directory.

Contents of build.yaml:
```
global_options:
  angular|component_source_cleanup:
    release_options:
      enabled: false
```
I really would appreciate to get a feedback from the maintainers about this solution, in order to know if this is indeed expected to be done by the developer or if it is a workaround.

Thanks!
