### ISSUE TITLE
pub-get fails with:

### ISSUE THREAD

**Issue by ronlobo** [dart-league/ng_bootstrap#20]
```
Could not find asset bootstrap_sass|lib/scss/_alert.scss.
package:pub/src/barback/pub_package_provider.dart 110  PubPackageProvider._assertExists
package:pub/src/barback/pub_package_provider.dart 104  PubPackageProvider.getAsset.<async>
```

Any idea?

my pubspec.yml:

```
name: ng_bootstrap_dashboard
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.18
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  ng_bootstrap: any
  sass: any
transformers:
- sass
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
```
