### ISSUE TITLE
Add description about how to load the font-awesome css

### ISSUE THREAD

**Issue by sturmf** [dart-league/ng_bootstrap#43]
Hi, 

since I am a beginner with this package it took me a while to figure out that ng_bootstrap brings font_awesome with it. I think the installation should mention that fact.

E.g. add: 

`<link rel="stylesheet" href="packages/font_awesome/css/font-awesome.min.css">`

to the installation instructions.

**Comment by luisvt** [comment]
you don't need to add anymor `font-awesome.min.css` you should use `ng_bootstrap/all.css`

**Comment by sturmf** [comment]
Hmm this is strange, I can see that the all.css on the ng_bootstrap website has the font-awesome css part concatenated at the end.

I have the following pubspec.yaml and run pub serve on my machine but don't get it appended.

```
name: frontend
description: Regatta frontend
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.20
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  http: ^0.11.0
  stream_transformers: ^0.3.0
  ng_bootstrap: any
  sass_transformer: any
  reflectable: any
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- reflectable:
    entry_points:
      - web/main.dart
    formatted: true
- dart_to_js_script_rewriter
- sass_transformer

```
