### ISSUE TITLE
all.css file can't be loaded.

### ISSUE THREAD

**Issue by avstudios** [dart-league/ng_bootstrap#48]
When I'm using WebStorm or command line to serve my app I'm getting the same error:
`[web] GET packages/ng_bootstrap/all.css => Could not find asset ng_bootstrap|lib/all.css.`
I've tested it with 1.9.0, 1.9.1 and 1.20.0-dev.10.2 dart sdk. So when packages dir is generated or not. The odd thing all is fine at my work but not on my laptop at home.  
This is my pubspec.yaml file:

```
name: app
description: app
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.22
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  firebase3:
    git: https://github.com/Janamou/firebase3-dart.git
  ng_bootstrap:
    git: https://github.com/dart-league/ng_bootstrap.git
  sass_transformer: any
transformers:
- sass_transformer
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
```

**Comment by avstudios** [comment]
I've just updated dependencies after changing `ng_bootstrap` to `any`. And I've got that error in Messages panel:

```
[sass_transformer] processing: ng_bootstrap|lib/all.scss
[sass_transformer] includePaths: {packages/ng_bootstrap}
Exception: Error: File to import not found or unreadable: packages/bootstrap_sass/scss/bootstrap.
       Load paths:
         /Users/user/Repos/app/packages/ng_bootstrap
         /Users/user/Repos/app (DEPRECATED)
        on line 3 of standard input
  Use --trace for backtrace.
```

I hope that tell you where is the problem. I don't know myself how to make it work.

**Comment by sandrobilbeisi** [comment]
I have seen that error a few times ...

I solved it temporarily by copying over from

> ng_bootstrap-master/build/web/packages/ng_bootstrap/all.css

to

> ng_bootstrap-master/lib/all.css

you can do this even _AFTER_ launching `pub serve`

**Comment by crazymanjinn** [comment]
Seeing the same issue when using `pub serve` and then going to localhost:8080 in dartium:

```
pub serve
Loading source assets...
Loading sass_transformer, angular2 and dart_to_js_script_rewriter transformers...
Serving frontend web on http://localhost:8080
Build completed successfully
[web] GET  → frontend|web/index.html
[web] GET packages/ng_bootstrap/all.css → Could not find asset ng_bootstrap|lib/all.css.
[web] GET Served 474 assets.
```

Using `pub build` and then opening the resulting `index.html` in browser has no issue. Can do a manual fix by copying the built version of `all.css` into `.pub/deps/debug/ng_bootstrap/lib`

```
cp build/web/packages/ng_bootstrap/all.css .pub/deps/debug/ng_bootstrap/lib
```

`pubspec.yaml`:

```
name: frontend
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.22
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.2
  ng_bootstrap: any
  sass_transformer: any
transformers:
- sass_transformer
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
```

Dart/pub versions:

```
pub --version
Pub 1.19.1
dart --version
Dart VM version: 1.19.1 (Wed Sep  7 08:59:17 2016) on "macos_x64"
```

**Comment by sandrobilbeisi** [comment]
if you do `pub build` or `pub serve` then you can view the results in any browser , not just Dartium

**Comment by crazymanjinn** [comment]
Yeah if I use Chrome/Firefox, I see the exact same behavior. 

`pub serve` gives an error about missing `all.css`, but `pub build` works fine, and copying `all.css` out of the `build/...` folder into `.pubs/....` causes `pub serve` to work.

**Comment by sandrobilbeisi** [comment]
you can launch  `pub serve` and then manually tweak `ng_bootstrap-master/lib/all.css` and then reload the browser or use technologies such as LiveReload to edit the style in live-coding ...

**Comment by luisvt** [comment]
this is caused because the `packages` folder is not created anymore when you do `pub get`. A work around is to use:

```
pub get  --packages-dir
```

Previous command will create the `packages` folder and `sass` will be able to look into this folder to process the dependencies file.

**Comment by felipefv** [comment]
I'm having a similar problem on Windows 10, WebStorm 2018.2.5 (Build #WS-182.4892.25, built on October 18, 2018) and Dart 2.0.0.

This is my pubspec.yaml:

```
name: angular_test_app
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  angular_forms: any
  ng_bootstrap: any
  http: any

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
```

When running the app from within Webstorm **it works as expected**. However, when building it for deployment, the resulting app will miss all.css. Seems like all.scss didn't get compiled for some reason. But why just when building?

Thanks in advance.
