### ISSUE TITLE
bootstrap_sass dependency cannot be filled

### ISSUE THREAD

**Issue by ahirschberg** [dart-league/ng_bootstrap#60]
when running `pub get`:
```
Resolving dependencies... 
Package bootstrap_sass has no versions that match 4.0.0-alpha.3+5 derived from:
- ng_bootstrap 0.4.6 depends on version 4.0.0-alpha.3+5
```

The dependencies section of my pubspec.yaml:
```yaml
dependencies:
  angular2: 2.2.0
  browser: any
  dart_to_js_script_rewriter: any
  js: any
  ace: any
  ng_bootstrap: 0.4.6
  jsonx: any
  fff: any
  sass: any
```
Because it depends on an alpha version, do I need to enable that in pub somewhere? If so, this should be included in the install instructions or the bootstrap_sass version should be bumped to non-alpha.

It's been a while since I updated the dependencies on this project, updating from angular2 2.0.0-beta.20, so there may be some issue there as well.
